### ISSUE TITLE
DirectorJobRunner: execution expired

### ISSUE THREAD

**Issue by gowriln** [cloudfoundry/bosh-init#129]
Hi , 

I am facing following issue with bosh deploy on Openstack
Error : 
```
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 15
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc
  Started compiling packages > cli/6e22370bfb380059b856a1b397bc14ae9ec1633c
  Started compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf
  Started compiling packages > nginx/2f6ac4678d6c4bee5df717c030acf5c2c90c5eae
  Started compiling packages > ruby-2.3/de0e32fdb5507dfe2dd649cf8636f237f261b940
  Started compiling packages > libpq/9fd5ba9df67618785fcc839bececa1dcc449af13
   Failed compiling packages > nginx/2f6ac4678d6c4bee5df717c030acf5c2c90c5eae: execution expired (00:01:23)
   Failed compiling packages > libpq/9fd5ba9df67618785fcc839bececa1dcc449af13: execution expired (00:01:24)
   Failed compiling packages > cli/6e22370bfb380059b856a1b397bc14ae9ec1633c: execution expired (00:01:24)
   Failed compiling packages > ruby-2.3/de0e32fdb5507dfe2dd649cf8636f237f261b940: execution expired (00:01:24)
   Failed compiling packages > cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc: execution expired (00:01:24)
   Failed compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf: execution expired (00:01:24)

Error 100: execution expired

Task 15 error
```

 bosh task 15 --debug
```

D, [2017-09-05 06:29:02 #31031] [task:15] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"d8212224-c0de-4541-9c51-1ee3ebc51d15","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'CF-OpenstackIN' against Director '8a4d1cf8-334c-44c0-a70e-b036ed0cb562': #<Bosh::Clouds::VMCreationFailed: execution expired>","created_at":1504592942}
E, [2017-09-05 06:29:02 #31031] [task:15] ERROR -- DirectorJobRunner: execution expired
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_cpi-1.3262.15.0/lib/cloud/external_cpi.rb:119:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_cpi-1.3262.15.0/lib/cloud/external_cpi.rb:88:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_cpi-1.3262.15.0/lib/cloud/external_cpi.rb:51:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/vm_creator.rb:158:in `create'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/vm_creator.rb:54:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:145:in `create_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:186:in `instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:16:in `with_reused_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:115:in `prepare_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:66:in `block in compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:59:in `compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:204:in `block (2 levels) in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:202:in `block in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.15.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:198:in `process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.15.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:162:in `block (4 levels) in compile_packages'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.15.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.15.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.15.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-09-05 06:29:02 #31031] [task:15] DEBUG -- DirectorJobRunner: (0.000398s) SELECT NULL
D, [2017-09-05 06:29:02 #31031] [task:15] DEBUG -- DirectorJobRunner: (0.000134s) BEGIN
D, [2017-09-05 06:29:02 #31031] [task:15] DEBUG -- DirectorJobRunner: (0.000846s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-09-05 06:29:02.841931+0000', "description" = 'create deployment', "result" = 'execution expired', "output" = '/var/vcap/store/director/tasks/15', "checkpoint_time" = '2017-09-05 06:27:33.104631+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'CF-OpenstackIN', "started_at" = '2017-09-05 06:27:33.104555+0000' WHERE ("id" = 15)
D, [2017-09-05 06:29:02 #31031] [task:15] DEBUG -- DirectorJobRunner: (0.009292s) COMMIT
I, [2017-09-05 06:29:02 #31031] []  INFO -- DirectorJobRunner: Task took 1 minute 29.753786720999997 seconds to process.

Task 15 error
```
Any suggestions ?
Thanks

**Comment by dpb587-pivotal** [comment]
Sorry, it looks like we lost track of this and this is an older repo. I don't recognize this particular error.

It does look like you're using older versions of at least director, you may want to try upgrading both director and OpenStack - this may have been fixed by one or both of them.
